
service: CsharpHandlers

provider:
  name: aws
  runtime: dotnetcore2.1
  region: us-east-1
  
package:
  artifact: bin/release/netcoreapp2.1/deploy-package.zip

functions:
  api:
    handler: CsharpHandlers::CsharpHandlers.LambdaEntryPoint::FunctionHandlerAsync
    events:
     - http:
         path: /{proxy+}
         method: ANY

  hello:
    handler: CsharpHandlers::CsharpHandlers.Services.Handler::Hello